int main(void) {
    machine.cpu = &cpu;
    machine.apu = &apu;
    machine.dma = &dma;
    machine.ppu = &ppu;
    machine.cart = &cart;
    machine.ram = ram;
    apu.dsp = &dsp;
    apu.spc = &spc;
    cart.ram = sram;
    cart.ramSize = sizeof(sram);
    g_rtl_game_info = &game;
    cpu.a = 0x1234;
    ram[0x70] = 8;
    host_extra = 17;
    unsigned char *snapshot = malloc(1024 * 1024);
    assert(snapshot);
    size_t size = RtlSaveSnapshotToMemory(snapshot, 1024 * 1024);
    assert(size > 0x20000);
    cpu.a = 0x5678;
    cpu.e = true;
    ram[0x70] = 9;
    host_extra = 42;
    machine.joypad1Index = 11;
    machine.joypadConnected = 15;
    dsp.outputRecoveryRemaining = 89;
    dsp.sampleRead = 99;
    const Cpu before_cpu = cpu;
    const Snes before_snes = machine;
    const Dsp before_dsp = dsp;
    static Apu before_apu;
    static Ppu before_ppu;
    before_apu = apu;
    before_ppu = ppu;
    const Spc before_spc = spc;
    const Dma before_dma = dma;
    unsigned char before_ram[sizeof(ram)];
    memcpy(before_ram, ram, sizeof(ram));
    snes_saveload_set_version(7);
    assert(RtlValidateSnapshotFromMemory(snapshot, size));
    assert(snes_saveload_get_version() == 7);
    assert(memcmp(&cpu, &before_cpu, sizeof(cpu)) == 0);
    assert(memcmp(&machine, &before_snes, sizeof(machine)) == 0);
    assert(memcmp(&dsp, &before_dsp, sizeof(dsp)) == 0);
    assert(host_extra == 42 && !reconciled && !presentation_resets && !locks);
    /* Includes truncation midway through CPU, PPU/WRAM, and the extra chunk. */
    const size_t cuts[] = {9, 300, size / 2, size - sizeof(host_extra) - 1, size - 1};
    for (size_t i = 0; i < sizeof(cuts) / sizeof(cuts[0]); ++i) {
        assert(!RtlValidateSnapshotFromMemory(snapshot, cuts[i]));
        assert(snes_saveload_get_version() == 7);
        assert(!RtlLoadSnapshotFromMemory(snapshot, cuts[i]));
        assert(memcmp(&cpu, &before_cpu, sizeof(cpu)) == 0);
        assert(memcmp(&machine, &before_snes, sizeof(machine)) == 0);
        assert(memcmp(&dsp, &before_dsp, sizeof(dsp)) == 0);
        assert(memcmp(&apu, &before_apu, sizeof(apu)) == 0);
        assert(memcmp(&ppu, &before_ppu, sizeof(ppu)) == 0);
        assert(memcmp(&spc, &before_spc, sizeof(spc)) == 0);
        assert(memcmp(&dma, &before_dma, sizeof(dma)) == 0);
        assert(memcmp(ram, before_ram, sizeof(ram)) == 0);
        assert(host_extra == 42 && !reconciled && !presentation_resets && !locks);
        FILE *file = fopen("truncated.sav", "wb");
        assert(file && fwrite(snapshot, 1, cuts[i], file) == cuts[i]);
        assert(fclose(file) == 0);
        assert(!RtlLoadSnapshot("truncated.sav"));
        assert(memcmp(&cpu, &before_cpu, sizeof(cpu)) == 0);
        assert(memcmp(&machine, &before_snes, sizeof(machine)) == 0);
        assert(memcmp(&dsp, &before_dsp, sizeof(dsp)) == 0);
        assert(memcmp(&apu, &before_apu, sizeof(apu)) == 0);
        assert(memcmp(&ppu, &before_ppu, sizeof(ppu)) == 0);
        assert(memcmp(&spc, &before_spc, sizeof(spc)) == 0);
        assert(memcmp(&dma, &before_dma, sizeof(dma)) == 0);
        assert(memcmp(ram, before_ram, sizeof(ram)) == 0);
        assert(host_extra == 42 && !reconciled && !presentation_resets && !locks);
    }
    uint32_t version;
    memcpy(&version, snapshot + 4, 4);
    uint32_t future = 99;
    memcpy(snapshot + 4, &future, 4);
    assert(!RtlLoadSnapshotFromMemory(snapshot, size));
    memcpy(snapshot + 4, &version, 4);
    assert(!RtlLoadSnapshotFromMemory(snapshot, RTL_SAV_MAX_SIZE + 1));
    assert(memcmp(&cpu, &before_cpu, sizeof(cpu)) == 0);
    /* Even an extension whose load walker unexpectedly overreads must roll
     * back its earlier guest and host writes before reporting failure. */
    overread_extra = true;
    assert(!RtlLoadSnapshotFromMemory(snapshot, size));
    assert(memcmp(&cpu, &before_cpu, sizeof(cpu)) == 0);
    assert(memcmp(&machine, &before_snes, sizeof(machine)) == 0);
    assert(memcmp(&dsp, &before_dsp, sizeof(dsp)) == 0);
    assert(memcmp(ram, before_ram, sizeof(ram)) == 0);
    assert(host_extra == 42 && !reconciled && !presentation_resets && !locks);
    assert(snes_saveload_get_version() == 7);
    overread_extra = false;
    assert(RtlLoadSnapshotFromMemory(snapshot, size));
    assert(cpu.a == 0x1234 && ram[0x70] == 8 && host_extra == 17);
    assert(reconciled == 1 && presentation_resets == 1 && !locks);
    free(snapshot);
    return 0;
}
