/* snes_cycles.h -- GENERATED by recompiler/snes_cycles.py. DO NOT EDIT.
 *
 * Authoritative 65816 / SNES cycle cost model, baked from the Python
 * authority so the runtime / reference engine never drifts from the
 * recompiler emitter. Regenerate with:
 *     python recompiler/snes_cycles.py --emit-c runner/src/snes/snes_cycles.h
 * Provenance and the full modifier rules live in snes_cycles.py.
 */
#ifndef SNES_CYCLES_H
#define SNES_CYCLES_H
#include <stdint.h>

/* Master-clock costs per memory access (21.47727 MHz master clock). */
#define SNES_CYC_FAST     6   /* 3.58 MHz */
#define SNES_CYC_SLOW     8   /* 2.68 MHz */
#define SNES_CYC_XSLOW   12   /* manual joypad / internal I/O */
#define SNES_CYC_INTERNAL SNES_CYC_FAST

/* Per-opcode static contributions (op = 1 byte). Combine via the inline
 * functions below; identical logic to snes_cycles.instr_cpu_cycles. */
static const uint8_t SNES_BASE_CYCLES[256] = {
     7, 6, 7, 4, 5, 3, 5, 6, 3, 2, 2, 4, 6, 4, 6, 5,
     2, 5, 5, 7, 5, 4, 6, 6, 2, 4, 2, 2, 6, 4, 7, 5,
     6, 6, 8, 4, 3, 3, 5, 6, 4, 2, 2, 5, 4, 4, 6, 5,
     2, 5, 5, 7, 4, 4, 6, 6, 2, 4, 2, 2, 4, 4, 7, 5,
     6, 6, 2, 4, 7, 3, 5, 6, 3, 2, 2, 3, 3, 4, 6, 5,
     2, 5, 5, 7, 7, 4, 6, 6, 2, 4, 3, 2, 4, 4, 7, 5,
     6, 6, 6, 4, 3, 3, 5, 6, 4, 2, 2, 6, 5, 4, 6, 5,
     2, 5, 5, 7, 4, 4, 6, 6, 2, 4, 4, 2, 6, 4, 7, 5,
     3, 6, 4, 4, 3, 3, 3, 6, 2, 2, 2, 3, 4, 4, 4, 5,
     2, 6, 5, 7, 4, 4, 4, 6, 2, 5, 2, 2, 4, 5, 5, 5,
     2, 6, 2, 4, 3, 3, 3, 6, 2, 2, 2, 4, 4, 4, 4, 5,
     2, 5, 5, 7, 4, 4, 4, 6, 2, 4, 2, 2, 4, 4, 4, 5,
     2, 6, 3, 4, 3, 3, 5, 6, 2, 2, 2, 3, 4, 4, 6, 5,
     2, 5, 5, 7, 6, 4, 6, 6, 2, 4, 3, 3, 6, 4, 7, 5,
     2, 6, 3, 4, 3, 3, 5, 6, 2, 2, 2, 3, 4, 4, 6, 5,
     2, 5, 5, 7, 5, 4, 6, 6, 2, 4, 4, 2, 8, 4, 7, 5,
};
static const uint8_t SNES_M_ADD[256] = {
     0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 2, 1, 2, 1,
     0, 1, 1, 1, 2, 1, 2, 1, 0, 1, 0, 0, 2, 1, 2, 1,
     0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1,
     0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1,
     0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
     0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
     0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
     0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
     0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
     0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1,
};       /* added when m==0 */
static const uint8_t SNES_X_ADD[256] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
     0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
     0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
     1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
};       /* added when x==0 */
static const uint8_t SNES_DP_ADD[256] = {
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
};     /* added when D.l != 0 */
static const uint8_t SNES_XCROSS_ADD[256] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
}; /* added when index crosses a page (read ops) */
static const uint8_t SNES_BRANCH_CLASS[256] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
}; /* 0 none, 1 conditional, 2 BRA */
static const uint8_t SNES_E_ADD[256] = {
     1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};       /* added in native mode (e==0): RTI/BRK/COP */
static const uint8_t SNES_OP_VALID[256] = {
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};   /* 1 if opcode decodes */
static const uint8_t SNES_OP_MODE[256] = {
     2,19, 2,13, 3, 3, 3,18, 0, 2, 1, 0, 6, 6, 6, 9,
    11,16,20,21, 3, 4, 4,17, 0, 8, 1, 0, 6, 7, 7,10,
     6,19, 9,13, 3, 3, 3,18, 0, 2, 1, 0, 6, 6, 6, 9,
    11,16,20,21, 4, 4, 4,17, 0, 8, 1, 0, 7, 7, 7,10,
     0,19, 2,13, 2, 3, 3,18, 0, 2, 1, 0, 6, 6, 6, 9,
    11,16,20,21, 2, 4, 4,17, 0, 8, 0, 0, 9, 7, 7,10,
     0,19,12,13, 3, 3, 3,18, 0, 2, 1, 0,14, 6, 6, 9,
    11,16,20,21, 4, 4, 4,17, 0, 8, 0, 0,15, 7, 7,10,
    11,19,12,13, 3, 3, 3,18, 0, 2, 0, 0, 6, 6, 6, 9,
    11,16,20,21, 4, 4, 5,17, 0, 8, 0, 0, 6, 7, 7,10,
     2,19, 2,13, 3, 3, 3,18, 0, 2, 0, 0, 6, 6, 6, 9,
    11,16,20,21, 4, 4, 5,17, 0, 8, 0, 0, 7, 7, 8,10,
     2,19, 2,13, 3, 3, 3,18, 0, 2, 0, 0, 6, 6, 6, 9,
    11,16,20,21, 3, 4, 4,17, 0, 8, 0, 0,14, 7, 7,10,
     2,19, 2,13, 3, 3, 3,18, 0, 2, 0, 0, 6, 6, 6, 9,
    11,16,20,21, 6, 4, 4,17, 0, 8, 0, 0,15, 7, 7,10,
};     /* addressing mode (SNES_MODE_*), 255 invalid */

/* Addressing-mode ids (mirror recompiler/snes65816.py constants). */
#define SNES_MODE_IMP       0
#define SNES_MODE_ACC       1
#define SNES_MODE_IMM       2
#define SNES_MODE_DP        3
#define SNES_MODE_DP_X      4
#define SNES_MODE_DP_Y      5
#define SNES_MODE_ABS       6
#define SNES_MODE_ABS_X     7
#define SNES_MODE_ABS_Y     8
#define SNES_MODE_LONG      9
#define SNES_MODE_LONG_X    10
#define SNES_MODE_REL       11
#define SNES_MODE_REL16     12
#define SNES_MODE_STK       13
#define SNES_MODE_INDIR     14
#define SNES_MODE_INDIR_X   15
#define SNES_MODE_INDIR_Y   16
#define SNES_MODE_INDIR_LY  17
#define SNES_MODE_INDIR_L   18
#define SNES_MODE_INDIR_DPX 19
#define SNES_MODE_DP_INDIR  20
#define SNES_MODE_STK_IY    21
#define SNES_MODE_INVALID 255

/* Master clocks for one access at a 24-bit address. memsel = $420D bit 0. */
static inline int snes_region_speed(uint32_t addr24, int memsel) {
    uint8_t bank = (uint8_t)(addr24 >> 16);
    uint16_t addr = (uint16_t)(addr24 & 0xFFFF);
    if (bank >= 0x40 && bank <= 0x7F) return SNES_CYC_SLOW;
    if (bank >= 0xC0)                 return memsel ? SNES_CYC_FAST : SNES_CYC_SLOW;
    if (addr >= 0x8000) {
        if (bank <= 0x3F)             return SNES_CYC_SLOW;       /* LoROM */
        return memsel ? SNES_CYC_FAST : SNES_CYC_SLOW;            /* WS2 LoROM */
    }
    if (addr < 0x2000)                return SNES_CYC_SLOW;       /* WRAM mirror */
    if (addr < 0x4000)                return SNES_CYC_FAST;       /* PPU/APU/I/O */
    if (addr < 0x4200)                return SNES_CYC_XSLOW;      /* joypad/I/O */
    if (addr < 0x6000)                return SNES_CYC_FAST;       /* $4200-$5FFF */
    return SNES_CYC_SLOW;                                         /* $6000-$7FFF */
}

/* MVN/MVP charge 7 master-equivalent CPU cycles PER BYTE moved; handle them
 * out of band (the byte count is the A register at execution). */
#define SNES_OP_IS_BLOCK_MOVE(op) ((op) == 0x44 || (op) == 0x54)

/* Total CPU (bus) cycles for one execution of `op`. Mirrors the Python
 * authority instr_cpu_cycles(); see snes_cycles.py for flag meanings. */
static inline int snes_instr_cpu_cycles(
        uint8_t op, int m, int x, int e,
        int dp_low_nonzero, int index_page_cross,
        int branch_taken, int branch_page_cross) {
    int c = SNES_BASE_CYCLES[op];
    if (m == 0) c += SNES_M_ADD[op];
    if (x == 0) c += SNES_X_ADD[op];
    if (dp_low_nonzero) c += SNES_DP_ADD[op];
    if (index_page_cross) c += SNES_XCROSS_ADD[op];
    switch (SNES_BRANCH_CLASS[op]) {
        case 1: /* conditional */
            if (branch_taken) { c += 1; if (e == 1 && branch_page_cross) c += 1; }
            break;
        case 2: /* BRA: base already counts the take */
            if (e == 1 && branch_page_cross) c += 1;
            break;
        default: break;
    }
    if (e == 0) c += SNES_E_ADD[op];
    return c;
}

#endif /* SNES_CYCLES_H */
